name: CI/CD Pipeline

on:
 push:
   branches:
     - master

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
      # Check Out Code
      - uses: actions/checkout@v3

      # Clear Composer Cache
      - name: Clear Composer Cache
        run: composer clear-cache

      # Install Composer
      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"

      # Composer to Install Dependencies with Various Extensions
      - uses: php-actions/composer@v6
        with:
          php_extensions: bcmath intl gd zip

      # Install Dependencies
      - run: npm install

      # Run PHP Unit Tests
      - run: vendor/bin/phpunit

      # Deploy The Project
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-keyscan -H 143.42.65.130 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh root@143.42.65.130 "cd /var/www/group-akaunting && git pull origin master"
          
      # Capture the Build History
      - name: Capture Build History
        run: |
          echo "Build started: $(date)" >> reports//build-history.txt
          echo "Commit: $(git rev-parse HEAD)" >> reports//build-history.txt
          echo "Branch: $(git rev-parse --abbrev-ref HEAD)" >> reports//build-history.txt

      # Generate Reports

        # History of the Build
      - name: Upload Build History Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-history
          path: reports/build-history.txt

        # Static Code Analysis
      - name: PHPStan Analysis
        run: vendor/bin/phpstan analyze --level=1 --memory-limit=512M --no-progress